apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: fintechops
  labels:
    app: admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3010"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: admin-service
          image: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops:admin-service-latest
          ports:
            - containerPort: 3010
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: fintechops-config
                  key: NODE_ENV
            - name: PORT
              value: "3010"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: fintechops-secrets
                  key: MONGODB_URI
            - name: POSTGRES_DB
              value: "fintechops"
            - name: POSTGRES_USER
              value: "fintechops"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintechops-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: fintechops-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: fintechops-config
                  key: POSTGRES_PORT
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: fintechops-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fintechops-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: fintechops
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
