apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintechops-production

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  # Single replica for testing
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ".*"

  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 5
    target:
      kind: HorizontalPodAutoscaler
      name: ".*"

# ============================================
# Image tags - Updated automatically by Jenkins CI
# Single ECR repo: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/fintechops
# Tags: <service>-<build_number>-<commit_hash>
# ============================================
images:
  - name: fintechops/frontend
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: frontend-latest
  - name: fintechops/api-gateway
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: api-gateway-latest
  - name: fintechops/auth-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: auth-service-latest
  - name: fintechops/user-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: user-service-latest
  - name: fintechops/calculator-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: calculator-service-latest
  - name: fintechops/market-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: market-service-latest
  - name: fintechops/news-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: news-service-latest
  - name: fintechops/blog-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: blog-service-latest
  - name: fintechops/chatbot-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: chatbot-service-latest
  - name: fintechops/email-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: email-service-latest
  - name: fintechops/admin-service
    newName: 836548370285.dkr.ecr.us-east-1.amazonaws.com/fintechops
    newTag: admin-service-latest
