apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fintechops-secrets
  namespace: fintechops
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "fintechops/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MONGODB_URI"
            objectAlias: "mongodb-uri"
          - path: "POSTGRES_URI"
            objectAlias: "postgres-uri"
          - path: "REDIS_URL"
            objectAlias: "redis-url"
      - objectName: "fintechops/api-keys"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_SECRET"
            objectAlias: "jwt-secret"
          - path: "GROQ_API_KEY"
            objectAlias: "groq-api-key"
          - path: "MARKET_API_KEY"
            objectAlias: "market-api-key"
          - path: "NEWS_API_KEY"
            objectAlias: "news-api-key"
      - objectName: "fintechops/aws-services"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "aws-access-key-id"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "aws-secret-access-key"
  secretObjects:
  - secretName: fintechops-secrets
    type: Opaque
    data:
    - objectName: mongodb-uri
      key: MONGODB_URI
    - objectName: postgres-uri
      key: POSTGRES_URI
    - objectName: redis-url
      key: REDIS_URL
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: groq-api-key
      key: GROQ_API_KEY
    - objectName: market-api-key
      key: MARKET_API_KEY
    - objectName: news-api-key
      key: NEWS_API_KEY
    - objectName: aws-access-key-id
      key: AWS_ACCESS_KEY_ID
    - objectName: aws-secret-access-key
      key: AWS_SECRET_ACCESS_KEY